export const PROPOSAL_WORKFLOW_NAME = '[kintone] 提案資料生成';
export const PROPOSAL_PATH = 'exhibition-proposal';

export interface ProposalWorkflowConfig {
  webhookSecret: string;
  openaiApiKey: string;
  kintoneBaseUrl: string;
  opportunityAppId: number;
  opportunityApiToken: string;
  meetingLogAppId: number;
  meetingLogApiToken: string;
  boxClientId: string;
  boxClientSecret: string;
  boxEnterpriseId: string;
  boxFolderId: string;
  /** Generated by `buildPptxCodeNodeSource()` (src/lib/pptx-template.ts) from the real .pptx template at deploy time. */
  pptxCodeSource: string;
}

const PROPOSAL_CONTENT_SYSTEM_PROMPT = `あなたは大手コンサルティングファームのシニアセールスコンサルタントです。
与えられた案件情報(商談メモ・顧客の課題を含む)をもとに、顧客の経営陣・決裁者の心を動かす
提案資料の文章を日本語で生成します。

【必須原則】
1. 顧客の業種・状況に基づいた具体的な表現にする(汎用的・抽象的な表現は厳禁)。情報が少ない
   場合でも、案件名や概要から自然に推測できる範囲で具体的に書くこと。
2. 「何ができるか」ではなく「導入後に何が変わるか・いくら得するか」で語る。
3. 数字・期間を積極的に盛り込み、決裁者が即断できる説得力を持たせる。
4. 各フィールドの文字数上限を厳守すること。上限を超えると資料のレイアウトが崩れる
   (テキストボックスの高さは想定文字数に合わせて設計されている)。

回答は必ず次のJSON形式のみで返してください(説明文やコードブロックは不要)。括弧内の数字は
そのフィールドの文字数上限:
{
  "CLIENT_NAME": "顧客(取引先)名",
  "PROPOSAL_TITLE": "提案タイトル。「〇〇のご提案」ではなく経営課題と解決後の姿が伝わる表現(20字以内)",
  "PROPOSAL_SUBTITLE": "具体的な数字を含む価値提案(35字以内)",
  "CHALLENGE_1": "課題1。「〇〇が課題です」ではなく「〇〇により△△という損失が発生」の形式(35字以内)",
  "CHALLENGE_2": "課題2(35字以内)",
  "CHALLENGE_3": "課題3(35字以内)",
  "PROPOSAL_SUMMARY": "提案の本質的価値と期待成果、経営者視点(120字以内)",
  "KEY_POINT_1": "競合との最大差別化ポイント。数字を含める(30字以内)",
  "KEY_POINT_2": "定量的な導入効果・ROI(30字以内)",
  "KEY_POINT_3": "リスク最小化・安心感の根拠(30字以内)",
  "FEATURE_1": "機能1がもたらす業務変革効果(35字以内)",
  "FEATURE_2": "機能2の業務変革効果(35字以内)",
  "FEATURE_3": "機能3の業務変革効果(35字以内)",
  "FEATURE_4": "機能4の業務変革効果(35字以内)",
  "KPI_LABEL_1": "KPI指標名(15字以内)", "KPI_VALUE_1": "数値のみ(例: 42)", "KPI_UNIT_1": "単位(例: %削減、6字以内)", "KPI_NOTE_1": "試算根拠(45字以内)",
  "KPI_LABEL_2": "KPI指標名(15字以内)", "KPI_VALUE_2": "数値のみ", "KPI_UNIT_2": "単位(6字以内)", "KPI_NOTE_2": "試算根拠(45字以内)",
  "KPI_LABEL_3": "KPI指標名(15字以内)", "KPI_VALUE_3": "数値のみ", "KPI_UNIT_3": "単位(6字以内)", "KPI_NOTE_3": "試算根拠(45字以内)",
  "STEP_1_TITLE": "導入ステップ1のフェーズ名(18字以内)", "STEP_1_DESC": "主要タスク・成果物(55字以内)",
  "STEP_2_TITLE": "導入ステップ2のフェーズ名(18字以内)", "STEP_2_DESC": "主要タスク・成果物(55字以内)",
  "STEP_3_TITLE": "導入ステップ3のフェーズ名(18字以内)", "STEP_3_DESC": "主要タスク・成果物(55字以内)",
  "STEP_4_TITLE": "導入ステップ4のフェーズ名(18字以内)", "STEP_4_DESC": "主要タスク・成果物(55字以内)",
  "ITEM_1": "見積り項目1(20字以内)", "DESC_1": "項目1の説明(25字以内)",
  "ITEM_2": "見積り項目2(20字以内)", "DESC_2": "項目2の説明(25字以内)",
  "ITEM_3": "見積り項目3(20字以内)", "DESC_3": "項目3の説明(25字以内)",
  "ITEM_4": "見積り項目4(20字以内)", "DESC_4": "項目4の説明(25字以内)",
  "ACTION_1": "次のアクション1。担当者・具体的行動・ゴールを含む(45字以内)",
  "ACTION_2": "次のアクション2(45字以内)",
  "ACTION_3": "次のアクション3(45字以内)",
  "PRICING_NOTE": "価格の妥当性・含まれるサービス・保証内容(65字以内)"
}`;

function offsetPositions(startX: number, y: number, count: number, gap = 220): [number, number][] {
  return Array.from({ length: count }, (_, i) => [startX + i * gap, y]);
}

export function buildProposalWorkflow(config: ProposalWorkflowConfig) {
  const positions = offsetPositions(0, 0, 22);
  let p = 0;
  const nextPos = () => positions[p++];

  const opportunityHeader = () => [{ name: 'X-Cybozu-API-Token', value: config.opportunityApiToken }];
  const meetingLogHeader = () => [{ name: 'X-Cybozu-API-Token', value: config.meetingLogApiToken }];
  const openaiHeaders = () => [
    { name: 'Authorization', value: `Bearer ${config.openaiApiKey}` },
    { name: 'Content-Type', value: 'application/json' },
  ];
  const boxTokenBody = `grant_type=client_credentials&client_id=${config.boxClientId}&client_secret=${config.boxClientSecret}&box_subject_type=enterprise&box_subject_id=${config.boxEnterpriseId}`;

  const nodes = [
    {
      id: 'webhook',
      name: 'Webhook',
      type: 'n8n-nodes-base.webhook',
      typeVersion: 2,
      position: nextPos(),
      parameters: { httpMethod: 'POST', path: PROPOSAL_PATH, responseMode: 'responseNode' },
    },
    {
      id: 'verify_secret',
      name: 'Verify Secret',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: {
        jsCode: `
const expected = ${JSON.stringify(config.webhookSecret)};
const headers = $input.item.json.headers || {};
const provided = headers['x-webhook-secret'];
const body = $input.item.json.body || {};
return [{ json: { ...body, valid: provided === expected } }];
`.trim(),
      },
    },
    {
      id: 'secret_valid_if',
      name: 'Secret Valid?',
      type: 'n8n-nodes-base.if',
      typeVersion: 1,
      position: nextPos(),
      parameters: {
        conditions: {
          boolean: [{ value1: '={{$json.valid}}', value2: true }],
        },
      },
    },
    {
      id: 'respond_unauthorized',
      name: 'Respond Unauthorized',
      type: 'n8n-nodes-base.respondToWebhook',
      typeVersion: 1.1,
      position: [positions[2][0] + 220, positions[2][1] + 200] as [number, number],
      parameters: {
        respondWith: 'json',
        responseBody: '={{ { "error": "invalid webhook secret" } }}',
        options: { responseCode: 401 },
      },
    },
    {
      id: 'fetch_deal',
      name: 'Fetch Deal',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      parameters: {
        method: 'GET',
        url: `${config.kintoneBaseUrl}/k/v1/record.json`,
        sendHeaders: true,
        headerParameters: { parameters: opportunityHeader() },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'app', value: String(config.opportunityAppId) },
            { name: 'id', value: '={{ $json.recordId }}' },
          ],
        },
        options: {},
      },
    },
    {
      id: 'fetch_meeting_logs',
      name: 'Fetch Related Meeting Logs',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      parameters: {
        method: 'GET',
        url: `${config.kintoneBaseUrl}/k/v1/records.json`,
        sendHeaders: true,
        headerParameters: { parameters: meetingLogHeader() },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'app', value: String(config.meetingLogAppId) },
            {
              name: 'query',
              value:
                '={{ "deal_record_id = \\"" + $node["Verify Secret"].json.recordId.replace(/"/g, "") + "\\" order by $id desc limit 3" }}',
            },
          ],
        },
        options: {},
      },
    },
    {
      id: 'build_context',
      name: 'Build Context',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: {
        jsCode: `
const record = $node["Fetch Deal"].json.record;
const val = (f) => (f && f.value != null) ? f.value : '';

const customerName = val(record.account) || '(取引先未設定)';
const dealName = val(record.deal_name);
const amount = Number(val(record.amount)) || 0;
const stage = val(record.stage);
const closeDate = val(record.close_date);
const description = val(record.description);
const customerIssue = val(record.customer_issue);
const meetingNotes = val(record.meeting_notes);
const owner = val(record.owner);

const meetingLogs = $node["Fetch Related Meeting Logs"].json.records || [];
const meetingLogsText = meetingLogs.map((m) => '- 要約: ' + val(m.summary) + ' / ネクストアクション: ' + val(m.next_actions)).join('\\n');

const contextText = [
  '【案件情報】',
  '案件名: ' + dealName,
  '取引先: ' + customerName,
  '金額: ' + (amount ? amount + '円' : '未定'),
  'フェーズ: ' + stage,
  'クロージング予定日: ' + closeDate,
  '概要: ' + description,
  '',
  '【顧客の課題・商談メモ】',
  '顧客の課題: ' + (customerIssue || '(情報なし)'),
  '商談メモ: ' + (meetingNotes || '(情報なし)'),
  '',
  '【関連する商談ログ】',
  meetingLogsText || '(なし)',
].join('\\n');

const d = new Date();
const today = d.getFullYear() + '年' + (d.getMonth() + 1) + '月' + d.getDate() + '日';
const todayIso = d.toISOString().slice(0, 10);

function addMonths(base, m) {
  const dd = new Date(base);
  dd.setMonth(dd.getMonth() + m);
  return dd.toISOString().slice(0, 7);
}

// Mechanical placeholders computed deterministically (kept out of the AI prompt so pricing
// always sums correctly and dates are always real).
const p1 = Math.round(amount * 0.53);
const p2 = Math.round(amount * 0.20);
const p3 = Math.round(amount * 0.20);
const p4 = amount - p1 - p2 - p3;
function fmtY(n) { return n > 0 ? n.toLocaleString('ja-JP') : '-'; }
const amountStr = amount > 0 ? amount.toLocaleString('ja-JP') + '円（税抜）' : '別途御見積';

const mechanicalPlaceholders = {
  DATE: today,
  YOUR_COMPANY: 'Novagrid株式会社',
  QTY_1: '1式', PRICE_1: fmtY(p1), TOTAL_1: fmtY(p1),
  QTY_2: '1式', PRICE_2: fmtY(p2), TOTAL_2: fmtY(p2),
  QTY_3: '12ヶ月', PRICE_3: fmtY(Math.round(p3 / 12)), TOTAL_3: fmtY(p3),
  QTY_4: '1式', PRICE_4: fmtY(p4), TOTAL_4: fmtY(p4),
  GRAND_TOTAL: amountStr,
  STEP_1_PERIOD: todayIso.slice(0, 7),
  STEP_2_PERIOD: addMonths(todayIso, 1),
  STEP_3_PERIOD: addMonths(todayIso, 2),
  STEP_4_PERIOD: addMonths(todayIso, 4),
  ACTION_1_DATE: '1週間以内',
  ACTION_2_DATE: '2週間以内',
  ACTION_3_DATE: '1ヶ月以内',
};

return [{ json: {
  recordId: $node["Verify Secret"].json.recordId,
  customerName,
  dealName,
  today,
  contextText,
  mechanicalPlaceholders,
} }];
`.trim(),
      },
    },
    {
      id: 'generate_proposal_content',
      name: 'Generate Proposal Content',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      parameters: {
        method: 'POST',
        url: 'https://api.openai.com/v1/chat/completions',
        sendHeaders: true,
        headerParameters: { parameters: openaiHeaders() },
        sendBody: true,
        specifyBody: 'json',
        jsonBody: `={{ JSON.stringify({ model: "gpt-4o", response_format: { type: "json_object" }, messages: [ { role: "system", content: ${JSON.stringify(PROPOSAL_CONTENT_SYSTEM_PROMPT)} }, { role: "user", content: $json.contextText } ] }) }}`,
        options: {},
      },
    },
    {
      id: 'merge_placeholders',
      name: 'Merge Placeholders',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: {
        jsCode: `
const context = $node["Build Context"].json;
let parsed;
try {
  parsed = JSON.parse($json.choices[0].message.content);
} catch (e) {
  parsed = null;
}
if (!parsed || typeof parsed !== 'object') parsed = {};

const placeholders = { ...context.mechanicalPlaceholders, ...parsed };
if (!placeholders.CLIENT_NAME) placeholders.CLIENT_NAME = context.customerName;
if (!placeholders.PROPOSAL_TITLE) placeholders.PROPOSAL_TITLE = context.dealName || (context.customerName + ' 様 ご提案');

return [{ json: {
  recordId: context.recordId,
  customerName: context.customerName,
  dealName: context.dealName,
  today: context.today,
  placeholders,
} }];
`.trim(),
      },
    },
    {
      id: 'build_pptx',
      name: 'Build PPTX',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: { jsCode: config.pptxCodeSource },
    },
    {
      id: 'get_box_token',
      name: 'Get Box Token',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      parameters: {
        method: 'POST',
        url: 'https://api.box.com/oauth2/token',
        sendBody: true,
        contentType: 'raw',
        rawContentType: 'application/x-www-form-urlencoded',
        body: boxTokenBody,
        options: {},
      },
    },
    {
      id: 'prep_pptx_binary',
      name: 'Prep PPTX Binary',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: {
        jsCode: `
const built = $node["Build PPTX"].json;
const buffer = Buffer.from(built.base64, 'base64');
const binaryData = await this.helpers.prepareBinaryData(
  buffer,
  built.fileName,
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
);
return [{ json: { fileName: built.fileName }, binary: { pptx: binaryData } }];
`.trim(),
      },
    },
    {
      id: 'upload_to_box',
      name: 'Upload to Box',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      onError: 'continueRegularOutput',
      parameters: {
        method: 'POST',
        url: 'https://upload.box.com/api/2.0/files/content',
        sendHeaders: true,
        headerParameters: {
          parameters: [{ name: 'Authorization', value: '={{ "Bearer " + $node["Get Box Token"].json.access_token }}' }],
        },
        sendBody: true,
        contentType: 'multipart-form-data',
        bodyParameters: {
          parameters: [
            {
              parameterType: 'formData',
              name: 'attributes',
              value: `={{ JSON.stringify({ name: $json.fileName, parent: { id: ${JSON.stringify(config.boxFolderId)} } }) }}`,
            },
            { parameterType: 'formBinaryData', name: 'file', inputDataFieldName: 'pptx' },
          ],
        },
        options: {},
      },
    },
    {
      id: 'resolve_box_file_id',
      name: 'Resolve Box File ID',
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: nextPos(),
      parameters: {
        jsCode: `
const uploadResult = $json;
let fileId = null;
if (uploadResult.entries && uploadResult.entries[0]) {
  fileId = uploadResult.entries[0].id;
} else {
  // 409 conflict (a file with this name already exists in the folder). The generated filename
  // now includes a seconds-granular timestamp (see pptx-template.ts), so this should only ever
  // fire on a genuine double-submit rather than "same customer, same day" as before — falling
  // back to whatever file already has this name is a reasonable last resort here, not a silent
  // stale-content bug. Box file IDs are 10+ digit numbers, and appear nowhere else in the error
  // payload, so this regex reliably extracts it.
  const errMsg = (uploadResult.error && uploadResult.error.message) || JSON.stringify(uploadResult);
  const m = errMsg.match(/[0-9]{10,}/);
  if (m) fileId = m[0];
}
return [{ json: { fileId } }];
`.trim(),
      },
    },
    {
      id: 'create_box_share_link',
      name: 'Create Box Share Link',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      onError: 'continueRegularOutput',
      parameters: {
        method: 'PUT',
        url: '={{ "https://api.box.com/2.0/files/" + $json.fileId + "?fields=shared_link" }}',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Authorization', value: '={{ "Bearer " + $node["Get Box Token"].json.access_token }}' },
            { name: 'Content-Type', value: 'application/json' },
          ],
        },
        sendBody: true,
        contentType: 'raw',
        rawContentType: 'application/json',
        body: '{"shared_link":{"access":"open","permissions":{"can_view":true,"can_download":true}}}',
        options: {},
      },
    },
    {
      id: 'write_back',
      name: 'Write Back',
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: nextPos(),
      parameters: {
        method: 'PUT',
        url: `${config.kintoneBaseUrl}/k/v1/record.json`,
        sendHeaders: true,
        headerParameters: {
          parameters: [...opportunityHeader(), { name: 'Content-Type', value: 'application/json' }],
        },
        sendBody: true,
        specifyBody: 'json',
        jsonBody: `={{ JSON.stringify({ app: ${config.opportunityAppId}, id: Number($node["Merge Placeholders"].json.recordId), record: { proposal_url: { value: ($json.shared_link && $json.shared_link.url) || '' }, proposal_status: { value: ($json.shared_link && $json.shared_link.url) ? "完了" : "エラー" }, proposal_generated_at: { value: new Date().toISOString() } } }) }}`,
        options: {},
      },
    },
    {
      id: 'respond',
      name: 'Respond',
      type: 'n8n-nodes-base.respondToWebhook',
      typeVersion: 1.1,
      position: nextPos(),
      parameters: {
        respondWith: 'json',
        responseBody: '={{ { success: !!($node["Create Box Share Link"].json.shared_link), boxUrl: ($node["Create Box Share Link"].json.shared_link && $node["Create Box Share Link"].json.shared_link.url) || null } }}',
      },
    },
  ];

  const connections = {
    Webhook: { main: [[{ node: 'Verify Secret', type: 'main', index: 0 }]] },
    'Verify Secret': { main: [[{ node: 'Secret Valid?', type: 'main', index: 0 }]] },
    'Secret Valid?': {
      main: [
        [{ node: 'Fetch Deal', type: 'main', index: 0 }],
        [{ node: 'Respond Unauthorized', type: 'main', index: 0 }],
      ],
    },
    'Fetch Deal': { main: [[{ node: 'Fetch Related Meeting Logs', type: 'main', index: 0 }]] },
    'Fetch Related Meeting Logs': { main: [[{ node: 'Build Context', type: 'main', index: 0 }]] },
    'Build Context': { main: [[{ node: 'Generate Proposal Content', type: 'main', index: 0 }]] },
    'Generate Proposal Content': { main: [[{ node: 'Merge Placeholders', type: 'main', index: 0 }]] },
    'Merge Placeholders': { main: [[{ node: 'Build PPTX', type: 'main', index: 0 }]] },
    'Build PPTX': { main: [[{ node: 'Get Box Token', type: 'main', index: 0 }]] },
    'Get Box Token': { main: [[{ node: 'Prep PPTX Binary', type: 'main', index: 0 }]] },
    'Prep PPTX Binary': { main: [[{ node: 'Upload to Box', type: 'main', index: 0 }]] },
    'Upload to Box': { main: [[{ node: 'Resolve Box File ID', type: 'main', index: 0 }]] },
    'Resolve Box File ID': { main: [[{ node: 'Create Box Share Link', type: 'main', index: 0 }]] },
    'Create Box Share Link': { main: [[{ node: 'Write Back', type: 'main', index: 0 }]] },
    'Write Back': { main: [[{ node: 'Respond', type: 'main', index: 0 }]] },
  };

  return { name: PROPOSAL_WORKFLOW_NAME, nodes, connections };
}
